server:
  port: 8001

spring:
  application:
    name: cloud-provider-service
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**
  freemarker:
    cache: false    #页面不加载缓存，修改即时生效

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型MySQL - @localhost
    driver-class-name: com.mysql.cj.jdbc.Driver       #mysql驱动包
    url: jdbc:mysql://127.0.0.1:3306/cloud2020?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

# eureka 相关配置
eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true
  client:
    # 是否在eureka中注册自己
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka
#      ,http://eureka7002.com:7002/eureka


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.atguigu.springcloud.entities       #所有Entity别名类所在包